# デプロイ反復試験 for Type4のActions Workflow
name: 'Type4Test_Actions'

# 実行トリガーの設定
on:
  workflow_dispatch:
    inputs:
      trigger:
        description: 'If run flow, input "DEVICE NAME".'
        required: true
        default: 'CICD-T4-REFSYS-0003'
      environment1:
        description: 'input "Test Number <検証シートNo>-<検証No>".'
        required: true
      environment2:
        description: 'input "Repeat Count".'
        type: string
        required: true
        default: '0'
  # push:
  #   branches: [ 'feature/sdna/repeat_deploy_actions_type4' ]

# 環境変数の定義
env:
  TARGET_DEVICE: ${{ github.event.inputs.trigger }}
  TEST_NUMBER: ${{ github.event.inputs.environment1 }}
  REPEAT_NUM: ${{ github.event.inputs.environment2 }}

# ジョブの設定
jobs:
  integration:
    # 開始トリガの確認
    if: ${{ github.event.inputs.trigger != 'test' && github.event.inputs.environment1 != '1-1' }}
    # 実行環境の設定
    name: Type4Test ${{ github.event.inputs.environment1 }}
    #runs-on: [ self-hosted, Retro-EB-Nano-10 ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Setup and Test
        id: repeat_deploy_test_setup_and_execute
        run: |
            echo Hello, world!
