# This workflow is for Make Document Sample.

name: Testworkflows

# Controls when the action will run.
on:
  push:
    branches: [ 'test/20230206' ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  ARTIFACT_NAME: 'output_test_file'
  BASE_FILE_PATH: './sample.adoc'
  PO_FILE_PATH: './sample.po'
  
jobs:
  test:
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: setup po4a
        run: |
          DEBIAN_FRONTEND=noninteractive sudo apt-get install -y --no-install-recommends po4a
          sudo apt install libunicode-linebreak-perl

      - name: make updatepo file
        run: |
          po4a-updatepoa -M utf-8 -f asciidoc -m ${{ env.BASE_FILE_PATH }} -p ${{ env.PO_FILE_PATH }}

      - name: archive artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.ARTIFACT_NAME }}
          path: ${{ env.PO_FILE_PATH }}
          retention-days: 1
        if: ${{ success() }}
